# Generated by Django 4.0.2 on 2022-02-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrivingSchool', '0002_enrollment_payment_schedule_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='instuctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DrivingSchool.instructor'),
        ),
    ]
