# Generated by Django 4.0.2 on 2022-02-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrivingSchool', '0005_rename_instuctor_schedule_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='instuctor',
            new_name='instructor',
        ),
    ]
