# Generated by Django 4.0.2 on 2022-02-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrivingSchool', '0006_rename_instuctor_enrollment_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_name',
            new_name='student',
        ),
    ]
