# Generated by Django 4.0.2 on 2022-02-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrivingSchool', '0008_rename_student_name_payment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='Firstname',
        ),
    ]
